Feature/clipboard
nilsteampassnet/TeamPass pull request #4539
Opened 2024-12-22 19:57 UTC by nilsteampassnet

Fixing #4528
Main idea is to remove library ClipboardJS in order to permit usage of async calls when copying data to clipboard. The change relies on the usage of navigator.clipboard instruction.

2024-12-23 10:24 UTC, corentin-soriano reviewed
I haven't tested it yet, I'll take care of it as soon as I can with the changes to the install!

2024-12-23 10:24 UTC, corentin-soriano commented on pages/items.js.php
> +                    }, <?php echo isset($SETTINGS['password_overview_delay']) === true ? $SETTINGS['password_overview_delay'] * 1000 : 4000; ?>);
Is `$SETTINGS['password_overview_delay']` an int?

2024-12-31 10:08 UTC, corentin-soriano commented
I encounter an error if I copy an empty password from the list of items:
![image](https://github.com/user-attachments/assets/74adce30-d43d-4e85-b4d5-80c11707c61a)
If I click on the button to display the password on an item without password, it is then broken for all other items
 (click on asterisks show it but not the eye):
![image](https://github.com/user-attachments/assets/23540c94-50db-4d16-9d04-cac35e90648a)
The clipboard is cleaned instantly while the auto-clear feature is disabled:
![image](https://github.com/user-attachments/assets/4fb5d354-f1a3-4717-9240-049c4af20d37)

I've noticed cases where the "copied to clipboard" message is not displayed on the copy of a username or URL. This usually happens when I open one item, then another.

2024-12-31 15:06 UTC, nilsteampassnet commented
@corentin-soriano thank you
The fix should handle this case.
Tested with empty password copied from items list
![image](https://github.com/user-attachments/assets/76e5363e-677f-4825-9f93-371b2033acb0)

I could not reproduce the other point.
If no password then we should not have the "copy" button
![image](https://github.com/user-attachments/assets/932f72ca-f826-4793-b086-69209517eec5)

I will have an eye on this point.

2025-01-06 08:59 UTC, corentin-soriano requested changes
To reproduce the other issue, I just open an item with empty password and click on the eye:
![image](https://github.com/user-attachments/assets/f1f52e85-c82e-49ff-8a72-de4f43bcac60)
Then the button doesn't show the password on all other items without refresh teampass:
![image](https://github.com/user-attachments/assets/f020813b-d8fc-4fe9-841e-34d68a4c4fa7)

2025-01-06 08:59 UTC, corentin-soriano commented on pages/items.js.php
> +                    }, <?php echo isset($SETTINGS['password_overview_delay']) && is_int($SETTINGS['password_overview_delay']) ? $SETTINGS['password_overview_delay'] * 1000 : 4000; ?>);
I think we need to check if the setting is greater than 0 too.
![image](https://github.com/user-attachments/assets/ce8a6875-882d-476a-ae22-84182c945e1c)

2025-01-07 05:32 UTC, nilsteampassnet commented on pages/items.js.php
> +                    }, <?php echo isset($SETTINGS['password_overview_delay']) && is_int($SETTINGS['password_overview_delay']) ? $SETTINGS['password_overview_delay'] * 1000 : 4000; ?>);
Hi @corentin-soriano 
Didn't catched the show icon from the start but ok I could reproduce.
I've changed the logic. If no password, an igllo icon is shown informing the user that no pwd exists for this item.

2025-01-07 08:20 UTC, corentin-soriano requested changes
I noticed one last issue on search page:
![image](https://github.com/user-attachments/assets/65508c19-0eb4-47a3-926f-e9cdfe28ebc0)

2025-01-07 08:20 UTC, corentin-soriano commented on pages/search.js.php
> +                        if (clipboardDuration === 0) {
`clipboardDuration` is a string so `clipboardDuration === 0` is always false.

2025-01-07 08:20 UTC, corentin-soriano commented on pages/items.js.php
> +                        if (clipboardDuration === 0) {
`clipboardDuration` is a string so `clipboardDuration === 0` is always false.

2025-01-07 08:20 UTC, corentin-soriano commented on pages/items.js.php
> +                                if (clipboardDuration === 0) {
`clipboardDuration` is a string so `clipboardDuration === 0` is always false.

2025-01-09 08:29 UTC, corentin-soriano requested changes

2025-01-09 08:29 UTC, corentin-soriano commented on pages/search.js.php
> +                            return;
Here we have a double error message:
![image](https://github.com/user-attachments/assets/04467bf8-3eb1-4290-a94c-6a14781b48b7)

I think the `error_fetching_password` here can be removed and we can directly do the `return`.

2025-01-09 08:29 UTC, corentin-soriano commented on pages/search.js.php
> +                document.getElementById('btn-copy-login').addEventListener('click', async function() {
I noticed that `#btn-copy-login` is missing on items without a login.
This causes an error and the search spinner is never removed:
![image](https://github.com/user-attachments/assets/b1cf5a96-a09c-4549-9887-4b3613387007)

2025-01-10 08:46 UTC, corentin-soriano approved these changes
Looks good to me!

2025-01-10 15:59 UTC, closed without merging